-- Compatibility: allow the existing student-device system to store iPad Air.
do $$
declare
  constraint_name text;
begin
  select conname into constraint_name
  from pg_constraint
  where conrelid = 'students'::regclass
    and contype = 'c'
    and pg_get_constraintdef(oid) like '%device_type%'
  limit 1;

  if constraint_name is not null then
    execute format('alter table students drop constraint %I', constraint_name);
  end if;

  alter table students
    add constraint students_device_type_check
    check (device_type in ('מחשב', 'אייפד', 'אייפד אייר', 'מחשב מיקוד מבט', 'אייפד פרו'));
end $$;


create table if not exists school_devices (
  id bigint generated by default as identity primary key,
  name text not null,
  device_type text not null check (device_type in ('אייפד', 'אייפד אייר', 'אייפד פרו', 'מחשב', 'ציוד אחר')),
  serial_number text,
  location text,
  status text not null default 'available' check (status in ('available', 'checked_out', 'repair', 'inactive')),
  notes text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists school_device_loans (
  id bigint generated by default as identity primary key,
  device_id bigint not null references school_devices(id) on delete restrict,
  borrower_id bigint not null references app_users(id) on delete restrict,
  checked_out_at timestamptz not null default now(),
  expected_return text,
  returned_at timestamptz,
  checkout_note text,
  return_note text,
  status text not null default 'open' check (status in ('open', 'returned'))
);

create table if not exists school_device_maintenance (
  id bigint generated by default as identity primary key,
  device_id bigint not null references school_devices(id) on delete restrict,
  loan_id bigint references school_device_loans(id) on delete set null,
  reporter_id bigint references app_users(id) on delete set null,
  handler_id bigint references app_users(id) on delete set null,
  note text not null,
  status text not null default 'open' check (status in ('open', 'progress', 'closed')),
  created_at timestamptz not null default now(),
  closed_at timestamptz
);

create table if not exists school_device_availability_blocks (
  id bigint generated by default as identity primary key,
  device_id bigint not null references school_devices(id) on delete cascade,
  day_of_week integer not null check (day_of_week between 0 and 6),
  start_time text not null check (start_time ~ '^[0-9]{2}:[0-9]{2}$'),
  end_time text not null check (end_time ~ '^[0-9]{2}:[0-9]{2}$'),
  note text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);


alter table school_devices enable row level security;
alter table school_device_loans enable row level security;
alter table school_device_maintenance enable row level security;
alter table school_device_availability_blocks enable row level security;

drop policy if exists "mvp anon access school_devices" on school_devices;
drop policy if exists "mvp anon access school_device_loans" on school_device_loans;
drop policy if exists "mvp anon access school_device_maintenance" on school_device_maintenance;
drop policy if exists "mvp anon access school_device_availability_blocks" on school_device_availability_blocks;

create policy "mvp anon access school_devices" on school_devices
  for all using (true) with check (true);

create policy "mvp anon access school_device_loans" on school_device_loans
  for all using (true) with check (true);

create policy "mvp anon access school_device_maintenance" on school_device_maintenance
  for all using (true) with check (true);

create policy "mvp anon access school_device_availability_blocks" on school_device_availability_blocks
  for all using (true) with check (true);

insert into school_devices (id, name, device_type, serial_number, location, status, notes, active) values
  (1, 'אייפד בית ספרי 01', 'אייפד', 'MSHI-IPAD-01', 'ארון תקשוב', 'available', 'כולל מגן ומטען', true),
  (2, 'אייפד אייר 02', 'אייפד אייר', 'MSHI-AIR-02', 'ארון תקשוב', 'available', 'מיועד להשאלה לפעילות כיתתית', true),
  (3, 'אייפד פרו 03', 'אייפד פרו', 'MSHI-PRO-03', 'חדר טיפול', 'repair', 'בדיקת עט ומקלדת', true)
on conflict (id) do nothing;

insert into school_device_maintenance (id, device_id, note, status, created_at) values
  (1, 3, 'בדיקה יזומה: לוודא שהעט נטען והמקלדת מתחברת.', 'open', '2026-06-24T12:00:00+03:00')
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('school_devices', 'id'), (select coalesce(max(id), 1) from school_devices));
select setval(pg_get_serial_sequence('school_device_loans', 'id'), (select coalesce(max(id), 1) from school_device_loans));
select setval(pg_get_serial_sequence('school_device_maintenance', 'id'), (select coalesce(max(id), 1) from school_device_maintenance));
select setval(pg_get_serial_sequence('school_device_availability_blocks', 'id'), (select coalesce(max(id), 1) from school_device_availability_blocks));
