begin;

-- Student import and profile fields.
alter table students
  add column if not exists notes text,
  add column if not exists grid_type text,
  add column if not exists camera_type text;

alter table students
  drop constraint if exists students_grid_type_check;

alter table students
  add constraint students_grid_type_check
  check (grid_type is null or grid_type in ('כן', 'לא', 'טאצ''ט'));

-- Accessibility dates can also contain values such as "אפריל 26" or "לא ברור".
alter table students
  drop constraint if exists students_accessibility_date_check;

alter table students
  drop constraint if exists students_care_provider_check;

alter table students
  add constraint students_care_provider_check
  check (
    care_provider is null
    or care_provider in ('משרד הבריאות', 'משרד החינוך', 'מחוץ למשי', 'קופת חולים כללית')
  );

-- Full request closure journal.
create table if not exists request_closures (
  id bigint generated by default as identity primary key,
  request_id bigint not null references tech_requests(id) on delete cascade,
  student_id bigint references students(id) on delete set null,
  closed_by_id bigint not null references app_users(id) on delete restrict,
  closure_type text not null check (
    closure_type in (
      'תיקון מחשב',
      'תיקון מסך',
      'החלפת מסך',
      'החלפת מצלמה',
      'תיקון שקע חיבור מטען',
      'אחר'
    )
  ),
  other_detail text,
  closing_message text not null default '',
  closed_at timestamptz not null default now(),
  check (closure_type <> 'אחר' or nullif(btrim(other_detail), '') is not null)
);

create index if not exists request_closures_request_id_idx
  on request_closures(request_id);

create index if not exists request_closures_student_id_idx
  on request_closures(student_id);

create index if not exists request_closures_closed_at_idx
  on request_closures(closed_at desc);

commit;
