create table if not exists request_treatment_updates (
  id bigint generated by default as identity primary key,
  request_id bigint not null references tech_requests(id) on delete cascade,
  author_id bigint references app_users(id) on delete set null,
  note text not null,
  created_at timestamptz not null default now()
);

alter table request_treatment_updates enable row level security;

drop policy if exists "mvp anon access request_treatment_updates" on request_treatment_updates;

create policy "mvp anon access request_treatment_updates" on request_treatment_updates
  for all using (true) with check (true);

select setval(pg_get_serial_sequence('request_treatment_updates', 'id'), (select coalesce(max(id), 1) from request_treatment_updates));
