create table if not exists app_users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  role text not null check (role in ('staff', 'handler', 'admin')),
  class_names text[] default '{}',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists students (
  id bigint generated by default as identity primary key,
  full_name text not null,
  class_name text not null,
  device_type text check (device_type in ('מחשב', 'אייפד', 'אייפד אייר', 'מחשב מיקוד מבט', 'אייפד פרו')),
  care_provider text check (care_provider in ('משרד הבריאות', 'משרד החינוך')),
  accessibility_date text check (accessibility_date is null or accessibility_date ~ '^[0-9]{2}/[0-9]{2}$'),
  device_responsibility text,
  device_responsibility_phone text,
  device_responsibility_email text,
  accessories text,
  apple_id text,
  apple_password text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists tech_requests (
  id bigint generated by default as identity primary key,
  requester_id bigint not null references app_users(id) on delete restrict,
  handler_id bigint references app_users(id) on delete set null,
  subject_type text not null check (subject_type in ('student', 'class')),
  student_id bigint references students(id) on delete set null,
  subject_name text not null,
  class_name text not null,
  request_type text not null,
  description text not null,
  attempted text default '',
  status text not null default 'new' check (status in ('new', 'progress', 'waiting', 'closed')),
  internal_note text,
  closing_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists request_treatment_updates (
  id bigint generated by default as identity primary key,
  request_id bigint not null references tech_requests(id) on delete cascade,
  author_id bigint references app_users(id) on delete set null,
  note text not null,
  created_at timestamptz not null default now()
);

create table if not exists school_devices (
  id bigint generated by default as identity primary key,
  name text not null,
  device_type text not null check (device_type in ('אייפד', 'אייפד אייר', 'אייפד פרו', 'מחשב', 'ציוד אחר')),
  serial_number text,
  location text,
  status text not null default 'available' check (status in ('available', 'checked_out', 'repair', 'inactive')),
  notes text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists school_device_loans (
  id bigint generated by default as identity primary key,
  device_id bigint not null references school_devices(id) on delete restrict,
  borrower_id bigint not null references app_users(id) on delete restrict,
  checked_out_at timestamptz not null default now(),
  expected_return text,
  returned_at timestamptz,
  checkout_note text,
  return_note text,
  status text not null default 'open' check (status in ('open', 'returned'))
);

create table if not exists school_device_maintenance (
  id bigint generated by default as identity primary key,
  device_id bigint not null references school_devices(id) on delete restrict,
  loan_id bigint references school_device_loans(id) on delete set null,
  reporter_id bigint references app_users(id) on delete set null,
  handler_id bigint references app_users(id) on delete set null,
  note text not null,
  status text not null default 'open' check (status in ('open', 'progress', 'closed')),
  created_at timestamptz not null default now(),
  closed_at timestamptz
);

create table if not exists school_device_availability_blocks (
  id bigint generated by default as identity primary key,
  device_id bigint not null references school_devices(id) on delete cascade,
  day_of_week integer not null check (day_of_week between 0 and 6),
  start_time text not null check (start_time ~ '^[0-9]{2}:[0-9]{2}$'),
  end_time text not null check (end_time ~ '^[0-9]{2}:[0-9]{2}$'),
  note text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

-- Compatibility alters for existing MVP databases.
alter table students
  add column if not exists device_responsibility_phone text,
  add column if not exists device_responsibility_email text;

alter table tech_requests
  add column if not exists handler_id bigint references app_users(id) on delete set null;

insert into app_users (id, name, email, role, class_names, active) values
  (1, 'דנה רוזן', 'dana@mashi.school', 'staff', array['ג׳ תקשורת', 'ד׳1'], true),
  (2, 'רותם הדר', 'rotem@mashi.school', 'handler', '{}', true),
  (3, 'אורי מנהל', 'admin@mashi.school', 'admin', '{}', true)
on conflict (email) do nothing;

insert into students (id, full_name, class_name, device_type, care_provider, accessibility_date, device_responsibility, device_responsibility_phone, device_responsibility_email, accessories, apple_id, apple_password, active) values
  (1, 'נועה לוי', 'ג׳ תקשורת', 'אייפד', 'משרד החינוך', '09/25', 'רכזת תקשוב', '03-0000000', 'tikshuv@mashi.school', 'מגן קשיח, מקלדת בלוטות׳', 'noa.apple@mashi.school', 'נשמר בכספת בית הספר', true),
  (2, 'יואב כהן', 'ד׳1', 'מחשב מיקוד מבט', 'משרד הבריאות', '11/25', 'קלינאית תקשורת', '03-0000001', 'clinic@mashi.school', 'מתקן שולחני, זרוע למסך', null, null, true),
  (3, 'מיכל אברהם', 'ב׳2', 'מחשב', 'משרד החינוך', '02/26', 'מחנכת הכיתה', '03-0000002', 'teacher@mashi.school', 'עכבר מותאם', null, null, true),
  (4, 'כיתת הדרכה קבוצתית', 'קבוצה רב גילית', null, null, null, null, null, null, null, null, null, true)
on conflict (id) do nothing;

insert into tech_requests (id, requester_id, handler_id, subject_type, student_id, subject_name, class_name, request_type, description, attempted, status, internal_note, created_at) values
  (101, 1, null, 'student', 1, 'נועה לוי', 'ג׳ תקשורת', 'התאמת טכנולוגיה מסייעת', 'נדרשת התאמת כלי תקשורת תומכת לשיעורי שפה.', 'נוסה שימוש בלוח מודפס, אך נדרש פתרון דיגיטלי נגיש.', 'new', null, '2026-06-23T09:00:00+03:00'),
  (102, 1, 2, 'class', null, 'כיתה ד׳1', 'ד׳1', 'הדרכה לצוות', 'מבקשות הדרכה קצרה על שימוש בטאבלטים בפעילות קבוצתית.', '', 'progress', 'לתאם עם רותם לשבוע הבא.', '2026-06-20T09:00:00+03:00'),
  (103, 2, null, 'student', 3, 'מיכל אברהם', 'ב׳2', 'תקלה בציוד', 'המחשב התקשורתי לא נטען באופן יציב במהלך היום.', 'הוחלף מטען, הבעיה נמשכת.', 'waiting', null, '2026-06-24T09:00:00+03:00')
on conflict (id) do nothing;

insert into school_devices (id, name, device_type, serial_number, location, status, notes, active) values
  (1, 'אייפד בית ספרי 01', 'אייפד', 'MSHI-IPAD-01', 'ארון תקשוב', 'available', 'כולל מגן ומטען', true),
  (2, 'אייפד אייר 02', 'אייפד אייר', 'MSHI-AIR-02', 'ארון תקשוב', 'available', 'מיועד להשאלה לפעילות כיתתית', true),
  (3, 'אייפד פרו 03', 'אייפד פרו', 'MSHI-PRO-03', 'חדר טיפול', 'repair', 'בדיקת עט ומקלדת', true)
on conflict (id) do nothing;

insert into school_device_maintenance (id, device_id, reporter_id, note, status, created_at) values
  (1, 3, 2, 'בדיקה יזומה: לוודא שהעט נטען והמקלדת מתחברת.', 'open', '2026-06-24T12:00:00+03:00')
on conflict (id) do nothing;

-- MVP access policies.
-- These are intentionally permissive so the prototype can read/write through the public anon key.
-- Before real production use, replace these with authenticated role-based RLS policies.
alter table app_users enable row level security;
alter table students enable row level security;
alter table tech_requests enable row level security;
alter table request_treatment_updates enable row level security;
alter table school_devices enable row level security;
alter table school_device_loans enable row level security;
alter table school_device_maintenance enable row level security;
alter table school_device_availability_blocks enable row level security;

drop policy if exists "mvp anon access app_users" on app_users;
drop policy if exists "mvp anon access students" on students;
drop policy if exists "mvp anon access tech_requests" on tech_requests;
drop policy if exists "mvp anon access request_treatment_updates" on request_treatment_updates;
drop policy if exists "mvp anon access school_devices" on school_devices;
drop policy if exists "mvp anon access school_device_loans" on school_device_loans;
drop policy if exists "mvp anon access school_device_maintenance" on school_device_maintenance;
drop policy if exists "mvp anon access school_device_availability_blocks" on school_device_availability_blocks;

create policy "mvp anon access app_users" on app_users
  for all using (true) with check (true);

create policy "mvp anon access students" on students
  for all using (true) with check (true);

create policy "mvp anon access tech_requests" on tech_requests
  for all using (true) with check (true);

create policy "mvp anon access request_treatment_updates" on request_treatment_updates
  for all using (true) with check (true);

create policy "mvp anon access school_devices" on school_devices
  for all using (true) with check (true);

create policy "mvp anon access school_device_loans" on school_device_loans
  for all using (true) with check (true);

create policy "mvp anon access school_device_maintenance" on school_device_maintenance
  for all using (true) with check (true);

create policy "mvp anon access school_device_availability_blocks" on school_device_availability_blocks
  for all using (true) with check (true);

select setval(pg_get_serial_sequence('app_users', 'id'), (select coalesce(max(id), 1) from app_users));
select setval(pg_get_serial_sequence('students', 'id'), (select coalesce(max(id), 1) from students));
select setval(pg_get_serial_sequence('tech_requests', 'id'), (select coalesce(max(id), 100) from tech_requests));
select setval(pg_get_serial_sequence('request_treatment_updates', 'id'), (select coalesce(max(id), 1) from request_treatment_updates));
select setval(pg_get_serial_sequence('school_devices', 'id'), (select coalesce(max(id), 1) from school_devices));
select setval(pg_get_serial_sequence('school_device_loans', 'id'), (select coalesce(max(id), 1) from school_device_loans));
select setval(pg_get_serial_sequence('school_device_maintenance', 'id'), (select coalesce(max(id), 1) from school_device_maintenance));
select setval(pg_get_serial_sequence('school_device_availability_blocks', 'id'), (select coalesce(max(id), 1) from school_device_availability_blocks));
