create table if not exists app_users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  role text not null check (role in ('staff', 'handler', 'admin')),
  class_names text[] default '{}',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists students (
  id bigint generated by default as identity primary key,
  full_name text not null,
  class_name text not null,
  device_type text check (device_type in ('מחשב', 'אייפד', 'מחשב מיקוד מבט', 'אייפד פרו')),
  care_provider text check (care_provider in ('משרד הבריאות', 'משרד החינוך')),
  accessibility_date text check (accessibility_date is null or accessibility_date ~ '^[0-9]{2}/[0-9]{2}$'),
  device_responsibility text,
  device_responsibility_phone text,
  device_responsibility_email text,
  accessories text,
  apple_id text,
  apple_password text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists tech_requests (
  id bigint generated by default as identity primary key,
  requester_id bigint not null references app_users(id) on delete restrict,
  subject_type text not null check (subject_type in ('student', 'class')),
  student_id bigint references students(id) on delete set null,
  subject_name text not null,
  class_name text not null,
  request_type text not null,
  description text not null,
  attempted text default '',
  status text not null default 'new' check (status in ('new', 'progress', 'waiting', 'closed')),
  internal_note text,
  closing_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into app_users (id, name, email, role, class_names, active) values
  (1, 'דנה רוזן', 'dana@mashi.school', 'staff', array['ג׳ תקשורת', 'ד׳1'], true),
  (2, 'רותם הדר', 'rotem@mashi.school', 'handler', '{}', true),
  (3, 'אורי מנהל', 'admin@mashi.school', 'admin', '{}', true)
on conflict (email) do nothing;

insert into students (id, full_name, class_name, device_type, care_provider, accessibility_date, device_responsibility, device_responsibility_phone, device_responsibility_email, accessories, apple_id, apple_password, active) values
  (1, 'נועה לוי', 'ג׳ תקשורת', 'אייפד', 'משרד החינוך', '09/25', 'רכזת תקשוב', '03-0000000', 'tikshuv@mashi.school', 'מגן קשיח, מקלדת בלוטות׳', 'noa.apple@mashi.school', 'נשמר בכספת בית הספר', true),
  (2, 'יואב כהן', 'ד׳1', 'מחשב מיקוד מבט', 'משרד הבריאות', '11/25', 'קלינאית תקשורת', '03-0000001', 'clinic@mashi.school', 'מתקן שולחני, זרוע למסך', null, null, true),
  (3, 'מיכל אברהם', 'ב׳2', 'מחשב', 'משרד החינוך', '02/26', 'מחנכת הכיתה', '03-0000002', 'teacher@mashi.school', 'עכבר מותאם', null, null, true),
  (4, 'כיתת הדרכה קבוצתית', 'קבוצה רב גילית', null, null, null, null, null, null, null, null, null, true)
on conflict (id) do nothing;

insert into tech_requests (id, requester_id, subject_type, student_id, subject_name, class_name, request_type, description, attempted, status, internal_note, created_at) values
  (101, 1, 'student', 1, 'נועה לוי', 'ג׳ תקשורת', 'התאמת טכנולוגיה מסייעת', 'נדרשת התאמת כלי תקשורת תומכת לשיעורי שפה.', 'נוסה שימוש בלוח מודפס, אך נדרש פתרון דיגיטלי נגיש.', 'new', null, '2026-06-23T09:00:00+03:00'),
  (102, 1, 'class', null, 'כיתה ד׳1', 'ד׳1', 'הדרכה לצוות', 'מבקשות הדרכה קצרה על שימוש בטאבלטים בפעילות קבוצתית.', '', 'progress', 'לתאם עם רותם לשבוע הבא.', '2026-06-20T09:00:00+03:00'),
  (103, 2, 'student', 3, 'מיכל אברהם', 'ב׳2', 'תקלה בציוד', 'המחשב התקשורתי לא נטען באופן יציב במהלך היום.', 'הוחלף מטען, הבעיה נמשכת.', 'waiting', null, '2026-06-24T09:00:00+03:00')
on conflict (id) do nothing;

-- MVP access policies.
-- These are intentionally permissive so the prototype can read/write through the public anon key.
-- Before real production use, replace these with authenticated role-based RLS policies.
alter table app_users enable row level security;
alter table students enable row level security;
alter table tech_requests enable row level security;

drop policy if exists "mvp anon access app_users" on app_users;
drop policy if exists "mvp anon access students" on students;
drop policy if exists "mvp anon access tech_requests" on tech_requests;

create policy "mvp anon access app_users" on app_users
  for all using (true) with check (true);

create policy "mvp anon access students" on students
  for all using (true) with check (true);

create policy "mvp anon access tech_requests" on tech_requests
  for all using (true) with check (true);

select setval(pg_get_serial_sequence('app_users', 'id'), (select coalesce(max(id), 1) from app_users));
select setval(pg_get_serial_sequence('students', 'id'), (select coalesce(max(id), 1) from students));
select setval(pg_get_serial_sequence('tech_requests', 'id'), (select coalesce(max(id), 100) from tech_requests));
